logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Meme-Tube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
excluded-patches = "theme"

[Meme-Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[Meme-Tok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "sim-spoof"

[Meme-Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Meme-Chat]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Meme-X]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[Memeigram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"

[Meme-Reddit Slide]
apkmirror-dlurl = "https://www.apkmirror.com/apk/haptic-apps/slide-for-reddit/slide-for-reddit-6-7-1-release/"
